title: Hello, world! I'm Rebecca Li
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: https://xiaoyang-rebecca.github.io # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Rebecca Li # add your name
author-img: ./figures/Rebeccca%20li.jpg # add your photo
about-author: I am a Data Scientist and a soon-to-gradute PhD at Univerisity of Houston. I have 5yrs of research and industrial experience in Deep Learning, Machine Learning, and Computer Vision. My industrial domain experience covers Medical Image, Self-driving Car and Oil & Gas. Always passion about real-world problems! # add description

social-github: http://github.com/Xiaoyang-Rebecca # add your Github handle
social-linkedin:http://linkedin.com/in/xiaoyang-rebecca-li # add your Linkedin handle
social-email:Xiaoyang.Rebecca.Li@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
